name: graphis
meta:
  copyright: MIT License, Copyright 2022 Eugene Ghanizadeh Khoub
  description: A convenient and stylish icon font
  url: https://loreanvictor.github.io/graphis/

metrics:
  height: 1160
  descent: 128

variations:
  - src: strokes
    name: Strokes
    build: false
    tests:
      - mappings
      - glyphs

  - src: regular
    weight: Regular
    name: Regular

  - src: bold
    weight: Bold
    style: Bold
    name: Bold
